### ISSUE TITLE
AttributeError in querymany

### ISSUE THREAD

**Issue by alexlenail** [biothings/mygene.info#11] opened 2017-04-29 01:21 UTC
After about 40,000 queries through a querymany, this error crops up:

```
.../Documents/project/venv/lib/python3.6/site-packages/mygene/__init__.py in querymany(self, qterms, scopes, **kwargs)
    569                 out.extend(hits)
    570                 for hit in hits:
--> 571                     if hit.get('notfound', False):
    572                         li_missing.append(hit['query'])
    573                     else:

AttributeError: 'str' object has no attribute 'get'
```

What's going on?

**Comment by namespacestd0** [comment] 2021-06-26 04:03
Can you provide a specific query for us to replicate the issue?

**Comment by newgene** [comment] 2021-07-12 21:29
Closing it for now, as we cannot reproduce the error. We can reopen it if the issue comes up again.

**Closed by newgene** 2021-07-12 21:29 UTC
